language: python
dist: xenial
sudo: required
python:
  - 3.6
  - 3.7
before_install:
  - sudo sh iptables_redir.sh
install:
  - python setup.py install
  - pip install codecov
script:
  - python setup.py test
after_success:
  - codecov
