name: Check Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - python setup.py install
    - pip install codecov
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
