name: Check Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: test
      run: python setup.py install
    - name: install
      run: pip install codecov
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
